### PR TITLE
Fail if parallel is not a numeric value

### LINKED ISSUE #408: --parallel appears to only work when it's the last arg
I ran into an issue with how the args are consumed

`ember exam --split 25 --reporter dot --parallel` will run the entire suite of tests but

`ember exam --split 25 --parallel --reporter dot` will only run the first partition

This is an issue if you've got your test command as `ember exam --split 25 --parallel` and want to change the reporters through the cli

### PR DESCRIPTION
**Pull request by step2yeung**
Fail if parallel is not a numeric value. This fixes #408

### CODE REVIEW

**Comment by choheekim** [comment]
LGTM! Thank you :)

File: lib/utils/tests-options-validator.js [hunk 1]
```diff
@@ -258,6 +258,14 @@ module.exports = class TestsOptionsValidator {
    * @return {boolean}
    */
   validateParallel() {
+    const parallelValue = parseInt(this.options.parallel);
```
Comment (rwjblue) [inline lib/utils/tests-options-validator.js]: Generally speaking, you should always pass a radix to `parseInt` (Note the radix does **not** default to 10!!!! [see MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)).

```suggestion
    const parallelValue = parseInt(this.options.parallel, 10);
```

Comment (step2yeung) [reply lib/utils/tests-options-validator.js]: Thanks @rwjblue !! Fixed!

**Comment by choheekim** [comment]
CI will be passing once rebase :) !
